name: Teemii ci-develop

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - develop

jobs:
  build-and-test-server:
    name: Lint & Test Build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install Dependencies
        run: npm install
        working-directory: ./server

      - name: Run Lint
        run: npm run lint
        working-directory: ./server

  build-and-push:
    name: Build & Publish Docker Images
    if: github.ref == 'refs/heads/develop' && !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            COMMIT_TAG=${{ github.sha }}
          tags: |
            dokkaner/teemii-backend:develop
            dokkaner/teemii-backend:${{ github.sha }}
            ghcr.io/dokkaner/teemii-backend:develop
            ghcr.io/dokkaner/teemii-backend:${{ github.sha }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            COMMIT_TAG=${{ github.sha }}
          tags: |
            dokkaner/teemii-frontend:develop
            dokkaner/teemii-frontend:${{ github.sha }}
            ghcr.io/dokkaner/teemii-frontend:develop
            ghcr.io/dokkaner/teemii-frontend:${{ github.sha }}