name: Publish Teemii Release

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

  build-and-push:
    needs: release
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Version from Tag
        id: extract_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            COMMIT_TAG=${{ github.sha }}
          tags: |
            dokkaner/teemii-backend:latest
            dokkaner/teemii-backend:${{ steps.extract_version.outputs.VERSION }}
            ghcr.io/dokkaner/teemii-backend:latest
            ghcr.io/dokkaner/teemii-backend:${{ steps.extract_version.outputs.VERSION }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            COMMIT_TAG=${{ github.sha }}
          tags: |
            dokkaner/teemii-frontend:latest
            dokkaner/teemii-frontend:${{ steps.extract_version.outputs.VERSION }}
            ghcr.io/dokkaner/teemii-frontend:latest
            ghcr.io/dokkaner/teemii-frontend:${{ steps.extract_version.outputs.VERSION }}