blank_issues_enabled: false
contact_links:
  - name: 💬 Support via GitHub Discussions
    url: https://github.com/dokkaner/teemii/discussions
    about: Ask questions and discuss with other community members